name: xeus-sqlite-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json >= 3.12
  - nlohmann_json-abi
  - xproperty < 0.13
  - cpp-tabulate
  - xvega
  - xvega-bindings
  - xeus-lite
  - xeus
  - xtl
  - sqlitecpp
